### ISSUE TITLE
Document exceeds on max allowed bson limit

### ISSUE THREAD

**Issue by musantro** [musantro/raceio#1]
When uploading a .csv file 8,3 MB, it does not store in MongoDB.

```
I20160224-11:11:53.229(1)? Exception while invoking method '/files/insert' Error: Document exceeds maximum allowed bson size of 16777216 bytes
I20160224-11:11:53.230(1)?     at Object.Future.wait (/home/musantro/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:395:16)
I20160224-11:11:53.230(1)?     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
I20160224-11:11:53.230(1)?     at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
I20160224-11:11:53.230(1)?     at [object Object].m.(anonymous function) (packages/mongo/collection.js:907:1)
I20160224-11:11:53.230(1)?     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
I20160224-11:11:53.231(1)?     at livedata_server.js:708:19
I20160224-11:11:53.231(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160224-11:11:53.231(1)?     at livedata_server.js:706:40
I20160224-11:11:53.231(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20160224-11:11:53.231(1)?     at livedata_server.js:704:46
I20160224-11:11:53.231(1)?     - - - - -
I20160224-11:11:53.231(1)?     at [object Object].QueryCommand.toBinary (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/commands/query_command.js:154:11)
I20160224-11:11:53.231(1)?     at [object Object].Connection.write (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection.js:265:37)
I20160224-11:11:53.231(1)?     at __executeQueryCommand (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1754:16)
I20160224-11:11:53.232(1)?     at Db._executeQueryCommand (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1904:7)
I20160224-11:11:53.232(1)?     at Db.command (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1185:8)
I20160224-11:11:53.232(1)?     at insertWithWriteCommands (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:101:20)
I20160224-11:11:53.232(1)?     at Collection.insert (/home/musantro/.meteor/packages/npm-mongo/.1.4.39_1.1klkbg5++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:31:7)
I20160224-11:11:53.232(1)?     at [object Object].MongoConnection._insert (packages/mongo/mongo_driver.js:363:1)
I20160224-11:11:53.232(1)?     at [object Object].<anonymous> (packages/meteor/helpers.js:118:1)
I20160224-11:11:53.232(1)?     at [object Object].MongoConnection.(anonymous function) [as insert] (packages/mongo/mongo_driver.js:736:1)
W20160224-11:17:51.851(1)? (STDERR)           
W20160224-11:17:51.852(1)? (STDERR) /home/musantro/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160224-11:17:51.853(1)? (STDERR)                         throw(ex);
W20160224-11:17:51.854(1)? (STDERR)                               ^
W20160224-11:17:51.857(1)? (STDERR) ReferenceError: Messages is not defined
W20160224-11:17:51.857(1)? (STDERR)     at server/seeder.js:2:2
W20160224-11:17:51.857(1)? (STDERR)     at /home/musantro/tfg/raceio/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
W20160224-11:17:57.728(1)? (STDERR)           
W20160224-11:17:57.728(1)? (STDERR) /home/musantro/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160224-11:17:57.728(1)? (STDERR)                         throw(ex);
W20160224-11:17:57.728(1)? (STDERR)                               ^
W20160224-11:17:57.732(1)? (STDERR) ReferenceError: Messages is not defined
W20160224-11:17:57.732(1)? (STDERR)     at server/seeder.js:2:2
W20160224-11:17:57.732(1)? (STDERR)     at /home/musantro/tfg/raceio/.meteor/local/build/programs/server/boot.js:249:5
=> Exited with code: 8
W20160224-11:18:03.181(1)? (STDERR)           
W20160224-11:18:03.182(1)? (STDERR) /home/musantro/.meteor/packages/meteor-tool/.1.1.10.ki0ccv++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160224-11:18:03.182(1)? (STDERR)                         throw(ex);
W20160224-11:18:03.182(1)? (STDERR)                               ^
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.
W20160224-11:18:03.185(1)? (STDERR) ReferenceError: Messages is not defined
W20160224-11:18:03.190(1)? (STDERR)     at server/seeder.js:2:2
W20160224-11:18:03.190(1)? (STDERR)     at /home/musantro/tfg/raceio/.meteor/local/build/programs/server/boot.js:249:5

```

**Comment by musantro** [comment]
This happened because I was storing the whole object into db. Parse each row or a chunk amount of rows is the key to save step-by-step into the db.
